import type { jsPDF } from "jspdf";

// Matches the app's CSS custom properties (globals.css) so every PDF reads
// as the same brand, not a generic document.
export const PDF_COLOR = {
  forest: [4, 120, 87] as const,
  forestDark: [6, 78, 59] as const,
  gold: [217, 119, 6] as const,
  maroon: [220, 38, 38] as const,
  ink: [15, 23, 42] as const,
  inkSoft: [82, 96, 109] as const,
  rule: [225, 228, 232] as const,
  bandFill: [240, 247, 244] as const, // faint forest tint for zebra rows
  headerFill: [6, 78, 59] as const,
};

export function setPdfColor(doc: jsPDF, target: "fill" | "text" | "draw", c: readonly [number, number, number]) {
  if (target === "fill") doc.setFillColor(c[0], c[1], c[2]);
  else if (target === "text") doc.setTextColor(c[0], c[1], c[2]);
  else doc.setDrawColor(c[0], c[1], c[2]);
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

/**
 * Logos can be uploaded as PNG, JPEG, WebP or SVG. jsPDF's addImage needs an
 * explicit raster format and can't embed SVG at all, so rasterize through a
 * canvas first — this works uniformly regardless of the source format.
 */
export async function rasterizeLogo(src: string): Promise<{ dataUrl: string; width: number; height: number } | null> {
  try {
    const img = await loadImage(src);
    const canvas = document.createElement("canvas");
    canvas.width = img.naturalWidth || 1;
    canvas.height = img.naturalHeight || 1;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    ctx.drawImage(img, 0, 0);
    return { dataUrl: canvas.toDataURL("image/png"), width: canvas.width, height: canvas.height };
  } catch {
    return null;
  }
}

export type PdfLetterheadData = {
  companyName: string;
  companyAddress?: string;
  companyContact?: string;
  companyGstin?: string;
  companyLogo?: string;
};

/** Draws the logo + company block and a gold accent rule. Returns the new y. */
export async function drawLetterhead(
  doc: jsPDF,
  marginX: number,
  pageWidth: number,
  startY: number,
  data: PdfLetterheadData
): Promise<number> {
  let y = startY;

  let logoBox: { w: number; h: number } | null = null;
  if (data.companyLogo) {
    const raster = await rasterizeLogo(data.companyLogo);
    if (raster) {
      const maxSize = 44;
      const ratio = raster.width / raster.height || 1;
      const w = ratio >= 1 ? maxSize : maxSize * ratio;
      const h = ratio >= 1 ? maxSize / ratio : maxSize;
      doc.addImage(raster.dataUrl, "PNG", marginX, y, w, h);
      logoBox = { w, h };
    }
  }

  const textX = marginX + (logoBox ? logoBox.w + 14 : 0);
  let ty = y + 4;
  setPdfColor(doc, "text", PDF_COLOR.forestDark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(data.companyName, textX, ty + 14);
  ty += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  setPdfColor(doc, "text", PDF_COLOR.inkSoft);
  const contactLines = [
    data.companyAddress,
    data.companyContact,
    data.companyGstin ? `GSTIN: ${data.companyGstin}` : undefined,
  ].filter(Boolean) as string[];
  for (const line of contactLines) {
    doc.text(line, textX, ty + 10);
    ty += 13;
  }

  y = Math.max(y + (logoBox?.h ?? 0), ty) + 12;
  setPdfColor(doc, "draw", PDF_COLOR.gold);
  doc.setLineWidth(2);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 28;

  return y;
}

/** Draws the "Generated by ... · date" + page number footer on every page. */
export function drawFooter(doc: jsPDF, marginX: number, pageWidth: number, pageHeight: number, companyName: string) {
  const totalPages = doc.getNumberOfPages();
  const generatedOn = new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date());
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    setPdfColor(doc, "draw", PDF_COLOR.rule);
    doc.setLineWidth(0.5);
    doc.line(marginX, pageHeight - 40, pageWidth - marginX, pageHeight - 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setPdfColor(doc, "text", PDF_COLOR.inkSoft);
    doc.text(`Generated by ${companyName} · ${generatedOn}`, marginX, pageHeight - 28);
    doc.text(`Page ${p} of ${totalPages}`, pageWidth - marginX, pageHeight - 28, { align: "right" });
  }
}

export function pdfFilename(base: string): string {
  return `${base.replace(/[^a-z0-9-]+/gi, "-")}.pdf`;
}
